/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jniproject_jnidemo_JNIUtils */

#ifndef _Included_com_example_jniproject_jnidemo_JNIUtils
#define _Included_com_example_jniproject_jnidemo_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jniproject_jnidemo_JNIUtils
 * Method:    getNativeString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jniproject_jnidemo_JNIUtils_getNativeString
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jniproject_jnidemo_JNIUtils
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_jniproject_jnidemo_JNIUtils_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_jniproject_jnidemo_JNIUtils
 * Method:    getPersonInfo
 * Signature: (Lcom/example/jniproject/jnidemo/JNIUtils/Person;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jniproject_jnidemo_JNIUtils_getPersonInfo
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
